import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import User from "../components/mypage";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>We care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <User />
    </div>
  );
};

export default Home;
