import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import PersonalInfo from "../components/personal_info";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>We care</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <PersonalInfo />
    </div>
  );
};

export default Home;
